# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      dhcp4: no
      addresses: [10.0.2.13/24]
      gateway4: 10.0.2.1
      nameservers:
        addresses: [127.0.0.1,8.8.8.8]
  version: 2
  renderer: networkd

